const WIDTH = 1200;
const HEIGHT = 700;
const GRID_SIZE = 50;

const COLOR_BACKGROUND_APP = '#f0f9ff';
const GRID_COLOR = '#cbd5e1';
const JOINT_COLOR = '#464646';
const BEAM_COLOR = '#8b4513';
const ANCHOR_COLOR = '#166534';
const HIGHLIGHT_COLOR = '#ef4444';
const SELECTION_COLOR = '#ef4444';
const SELECTED_FOR_LOAD_HIGHLIGHT_COLOR = '#06b6d4';
const TEMP_BEAM_COLOR = '#e5e5e5';
const LOAD_COLOR = '#f97316';
const LOAD_TEXT_COLOR = '#c2410c';
const REACTION_TEXT_COLOR = '#1e40af';

const JOINT_RADIUS = 8;
const HIGHLIGHT_RADIUS = 13;
const ANCHOR_Y_WORLD_THRESHOLD = 600;

const LOAD_MAGNITUDE = -1000;
const LOAD_INCREMENT_STEP = 100.0;
const MAX_FORCE_VIS = 2000;
const MAX_STRESS_VIS = 50e6;
const FLOAT_TOLERANCE = 1e-6;
const BEAM_DEFAULT_AREA = 0.001;

const TOOLBAR_HEIGHT = 48;
const SIDEBAR_WIDTH = 256;
const STATUSBAR_HEIGHT = 24;

const LOG_INFO = "[INFO] ";
const LOG_WARN = "[WARN] ";
const LOG_ERROR = "[ERROR] "; 